spring:
  application:
    name: ms-store
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: operational
  
  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
      transit:
        enabled: true
  
  threads:
    virtual:
      enabled: true
  
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: expedientes-top-secret
  part-size: 5242880

server:
  port: 8080

